### ISSUE TITLE
Model diverged with loss = NaN

### ISSUE THREAD

**Issue by linZHank** [linZHank/Intention_Prediction#1]
```ERROR:tensorflow:Model diverged with loss = NaN.
Traceback (most recent call last):
  File "pitch2d_main.py", line 320, in <module>
    tf.app.run()
  File "/home/linzhank/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "pitch2d_main.py", line 311, in main
    hooks=[logging_hook]) # used to have a "step" argument
  File "/home/linzhank/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 355, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/linzhank/.local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 903, in _train_model
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/linzhank/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 546, in run
    run_metadata=run_metadata)
  File "/home/linzhank/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1022, in run
    run_metadata=run_metadata)
  File "/home/linzhank/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1113, in run
    raise six.reraise(*original_exc_info)
  File "/home/linzhank/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1098, in run
    return self._sess.run(*args, **kwargs)
  File "/home/linzhank/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1178, in run
    run_metadata=run_metadata))
  File "/home/linzhank/.local/lib/python2.7/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 617, in after_run
    raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.
```
Even set learning rate = 0, still get this error. Must check the code thoroughly.

**Comment by linZHank** [comment]
Tried [this script](https://github.com/tensorflow/tensorflow/blob/r1.7/tensorflow/examples/tutorials/layers/cnn_mnist.py) using same model and input_fn. Wrote functions to read in images as grayscale\(one channel\), and  resize to \(28, 28\). Model was able to be trained. \
Looking forward to test code with color images\(3 channels\) and size of \(224, 224\)

**Comment by linZHank** [comment]
Load images to np arrays of \(num_examples, 224x224x3), then input to the alexnet model with tf.reshape(image_batch, [-1, 224, 224, 3]). With lr=0, the training lasts 100 steps; With lr=1e-5, training stops at first step and generate "NaN loss during training" error.\
Looks like this issue has nothing to do with the input features shape, should focus on the cnn model structure.

**Comment by linZHank** [comment]
Went over the alexnet structure again, I found the overlapping pooling layer has wrong kernel size = 2 (should be 3). Fix this brought me a training (lr=1e-4) last more than 100 steps, with lr=1e-5 even last over 300 steps.

**Comment by linZHank** [comment]
Refer to sparse_softmax_cross_entropy [doc](https://www.tensorflow.org/api_docs/python/tf/losses/sparse_softmax_cross_entropy)
`tf.losses.sparse_softmax_cross_entropy(labels, *)` Each entry in labels must be an index in [0, num_classes). So you'll have to make sure your labels starts from **0**.
